

    
analysis_name: analysis

multiprocessing: -1

material:
  definitions: materials_h5.h5
  active: ruby
  dmin: 1.0  # defaults to 1.0 angstrom
  tth_width: 0.25  # defaults to 0.25 degrees
  min_sfac_ratio: 0.05  # min percentage of max |F|^2 to exclude; default None

image_series:
  format: frame-cache
  data:
    - file: imageseries/mruby-0129_000004_ff2_000012-cachefile.npz
      args: {}
      panel: ff2  # must match detector key
    - file: imageseries/mruby-0129_000004_ff1_000012-cachefile.npz
      args: {}
      panel: ff1  # must match detector key

instrument: dexelas_id3a_20200130.yml


find_orientations:
  orientation_maps:
    # A file name must be specified. If it doesn't exist, one will be created
    file: analysis_ruby_eta-ome_maps.npz

fit_grains:
  do_fit: true # if false, extracts grains but doesn't fit. defaults to true
  # estimate: null
  npdiv: 2 # number of polar pixel grid subdivisions, defaults to 2
  threshold: 25

  tolerance:
    tth: [3.0] # tolerance lists must be identical length
    eta: [2.0]
    omega: [1.0]

  refit: [1.5,1.0]
  tth_max: true # true, false, or a non-negative value, defaults to true

